//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustMuesli.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuesliMixMuesli
    {
        public int MuesliMixId { get; set; }
        public int MuesliId { get; set; }
        public int Id { get; set; }
    
        public virtual Muesli Muesli { get; set; }
        public virtual MuesliMix MuesliMix { get; set; }
    }
}
